# Generated by Django 5.0.7 on 2024-08-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="owner",
        ),
    ]
