# Generated by Django 5.0.7 on 2024-08-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_base", "0003_rename_like_unlike_post_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="like",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
