# Generated by Django 5.0.7 on 2024-08-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_base", "0005_post_hashtags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="post",
            name="like",
        ),
    ]
