# Generated by Django 5.0.7 on 2024-08-28 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_base", "0006_remove_post_comment_remove_post_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="post_image",
        ),
    ]
