# Generated by Django 5.0.7 on 2024-08-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social_media_user", "0003_alter_user_managers_user_nickname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
