# Generated by Django 5.0.7 on 2024-08-22 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_user', '0006_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='my_subscriptions',
            field=models.ManyToManyField(blank=True, related_name='my_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
